build: make: add support for overriding CC and CXX
Clang complained with `-Werror,-Wstrict-prototypes` which caused me to
set `-std=c23` which I also wanted because of -Werror,-Wc23-extensions.

But setting `-std=c23` causes `-Werror=old-style-definition` for gcc.

Clang also failed with `error: use of undeclared identifier 'fileno'`
because that is guarded by `-D_POSIX_C_SOURCE`.

Clang then continued to fail with `conflicting types for 'malloc'` and
`conflicting types for 'symlook'`.

Also, clang apparently just does not know old style definitions at all.

We also got `-Wincompatible-pointer-types` from both gcc and clang.

With those out of the way there remained one curious ordering problem
that I could not fix with an additional rule: `%.tab.h` would just not
be created by calling both bison and flex before the first compile
action.

However, with these changes to the Makefile we now have much better
parallelism because each object file is compiled individually.

[1] https://www.man7.org/linux/man-pages/man3/fileno.3.html
[2] https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html