2026: mgl: adjust the generated code to current customs
  make -f Makefile.mgl VERBOSE=1 mgl-demo

Add a separate Makefile with updated instructions from page 106.
This Makefile partially duplicates the top-level Makefile for the sake
of making development of `mgl` as seamless as possible.

Prevent clash with `SCREEN` from `curses.h`:

  /usr/include/curses.h:453:24: note: previous declaration of ‘SCREEN’ with type ‘SCREEN’ {aka ‘struct screen’}
    453 | typedef struct screen  SCREEN;

Clang still complains because item_list appears to be nullptr all the
time:

  subr.c:191:6: error: variable 'cnt' set but not used [-Werror,-Wunused-but-set-variable]